### ISSUE TITLE
Installed seems to run in homebridge but...

### ISSUE THREAD

**Issue by sorriso93** [lucavb/homebridge-mi-flora#2]
I have two miflora, both are available in homekit rightnow but I get 0 for lux, 0 for humidity, zero for temperature, etc...
What is going wrong to your opinion?
I also get battery zero...
Thanks

**Comment by lucavb** [comment]
hey,

could you maybe post your configuration? without that I doubt I'll be able to say much. plus also make sure to use homebridge with elevated privileges, since it uses bluetooth.

**Comment by sorriso93** [comment]
Hello, 
configuration of homebridge? 4.38 is the last version, how can I get additional infos?

After some checks I have now hcitoolscan that is running ok on the raspberry (I can see the mac address of sensors).
Anyway now I get this error in the log. I gave homebridge user the one used by the process the root privileges, but I bet I should run it as root at this point?

Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:28:58 AM] Loading 4 accessories...
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:28:58 AM] [Limone Piccolo] Initializing mi-flower-care accessory...
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: noble warning: adapter state unauthorized, please run as root or with sudo
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]:                or see README for information on running without root/sudo:
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]:                https://github.com/sandeepmistry/noble#running-on-linux
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:28:58 AM] [Limone Grande] Initializing mi-flower-care accessory...
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:28:58 AM] [Fragole] Initializing mi-flower-care accessory...
Mar 21 02:28:58 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:28:58 AM] [Ciliegio] Initializing mi-flower-care accessory...

and then this

Mar 21 02:29:12 RASPBDIETPI homebridge[30170]: [3/21/2018, 2:29:12 AM] Homebridge is running on port 51826.
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]: noble warning: adapter state unauthorized, please run as root or with sudo
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]:                or see README for information on running without root/sudo:
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]:                https://github.com/sandeepmistry/noble#running-on-linux
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]: /usr/local/lib/node_modules/homebridge-mi-flower-care/node_modules/noble/lib/noble.js:100
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]:         throw error;
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]:         ^
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]: Error: Could not start scanning, state is unauthorized (not poweredOn)
Mar 21 02:29:14 RASPBDIETPI homebridge[30170]:     at Noble.scan (/usr/local/lib/node_modules/homebridge-mi-flower-care/node_modules/noble/lib/noble.js:95:19)

**Comment by sorriso93** [comment]
Changed the user in the service to root, no more errors in the log but same result:

root@RASPBDIETPI:~# journalctl -u homebridge
-- Logs begin at Wed 2018-03-21 02:35:06 CET, end at Wed 2018-03-21 02:42:05 CET. --
Mar 21 02:35:21 RASPBDIETPI systemd[1]: Started Node.js HomeKit Server.
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:35:47 RASPBDIETPI homebridge[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in t
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:35:47 RASPBDIETPI node[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 21 02:36:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:30 AM] Loaded plugin: homebridge-MotionSensor
Mar 21 02:36:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:30 AM] Registering accessory 'homebridge-MotionSensor.Motion'
Mar 21 02:36:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:30 AM] ---
Mar 21 02:36:31 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:31 AM] Loaded plugin: homebridge-config-ui-x
Mar 21 02:36:31 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:31 AM] Registering platform 'homebridge-config-ui-x.config'
Mar 21 02:36:31 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:31 AM] ---
Mar 21 02:36:31 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:31 AM] Loaded plugin: homebridge-harmonyhub
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] ---
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] Loaded plugin: homebridge-ip-camera
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] Registering platform 'homebridge-ip-camera.Camera-IP'
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] ---
Mar 21 02:36:40 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:40 AM] Loaded plugin: homebridge-mi-flower-care
Mar 21 02:36:47 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:47 AM] Registering accessory 'homebridge-mi-flower-care.mi-flower-care'
Mar 21 02:36:47 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:47 AM] ---
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] Loaded plugin: homebridge-netatmo
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] Registering platform 'homebridge-netatmo.netatmo'
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] ---
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] Loaded plugin: homebridge-suncalc
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] Registering accessory 'homebridge-suncalc.Suncalc'
Mar 21 02:36:51 RASPBDIETPI homebridge[439]: [3/21/2018, 2:36:51 AM] ---
Mar 21 02:37:00 RASPBDIETPI homebridge[439]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially
Mar 21 02:37:00 RASPBDIETPI node[439]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in t
Mar 21 02:37:00 RASPBDIETPI homebridge[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:37:00 RASPBDIETPI homebridge[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 21 02:37:00 RASPBDIETPI node[439]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 21 02:37:00 RASPBDIETPI node[439]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 21 02:37:00 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:00 AM] Loaded plugin: homebridge-wssensor
Mar 21 02:37:00 RASPBDIETPI homebridge[439]: homebridge API version: 2.2
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] Registering platform 'homebridge-wssensor.wssensor'
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] ---
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] Loaded config.json with 4 accessories and 4 platforms.
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] ---
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] Loading 4 platforms...
Mar 21 02:37:04 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:04 AM] [Netatmo] Initializing netatmo platform...
Mar 21 02:37:05 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:05 AM] [Harmony Hub] Initializing HarmonyHub platform...
Mar 21 02:37:05 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:05 AM] [Config] Initializing config platform...
Mar 21 02:37:08 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:08 AM] [Config] Using Form Authentication
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [Camera-IP] Initializing Camera-IP platform...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] Loading 4 accessories...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [Limone Piccolo] Initializing mi-flower-care accessory...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [Limone Grande] Initializing mi-flower-care accessory...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [Fragole] Initializing mi-flower-care accessory...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [Ciliegio] Initializing mi-flower-care accessory...
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: Load homebridge-wssensor.wssensor
Mar 21 02:37:28 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:28 AM] [homebridge-wssensor.wssensor] config undefined or null!
Mar 21 02:37:29 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:29 AM] [Config] Console is listening on port 8080.
Mar 21 02:37:29 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:29 AM] CAMCAMERA is running on port 45927.
Mar 21 02:37:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:30 AM] CAMSOGGIORNO is running on port 46283.
Mar 21 02:37:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:30 AM] CAMTERRCAM is running on port 46121.
Mar 21 02:37:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:30 AM] CAMBALCONE is running on port 46169.
Mar 21 02:37:30 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:30 AM] CAMTERRCUC is running on port 38821.
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:37 AM] [Netatmo] Initializing platform accessory 'M SAL'...
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:37 AM] [Netatmo] Initializing platform accessory 'M BALC'...
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:37 AM] [Netatmo] Initializing platform accessory 'TE'...
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: Setup Payload:
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: X-HM://0023ISYWYK84L
Mar 21 02:37:37 RASPBDIETPI homebridge[439]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                                                       
Mar 21 02:37:38 RASPBDIETPI homebridge[439]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                        
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:     ┌────────────┐
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:     │ 
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:     └────────────┘
Mar 21 02:37:38 RASPBDIETPI homebridge[439]:                        
Mar 21 02:37:38 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:38 AM] Homebridge is running on port 51826.
Mar 21 02:37:41 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:41 AM] [Harmony Hub] Fetching Logitech Harmony activities...
Mar 21 02:37:48 RASPBDIETPI homebridge[439]: [3/21/2018, 2:37:48 AM] [Harmony Hub] Found activities:
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Musica
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Clima OFF
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Radio
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         PowerOff
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Mac audio
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Clima ON auto
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Mac video
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Apple TV
Mar 21 02:37:48 RASPBDIETPI homebridge[439]:         Blue ray

**Comment by sorriso93** [comment]
Another update... still no data on homekit app but now in the log I get data!

Mar 21 10:48:34 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:34 AM] [Limone Grande] Lux: 778, Temperature: 18.6, Moisture: 37, Fertility: 2666
Mar 21 10:48:34 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:34 AM] [Limone Grande] Firmware: 3.1.8, Battery level: 99
Mar 21 10:48:35 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:35 AM] [Fragole] Lux: 5020, Temperature: 13.1, Moisture: 79, Fertility: 2540
Mar 21 10:48:35 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:35 AM] [Fragole] Firmware: 3.1.8, Battery level: 99
Mar 21 10:48:41 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:41 AM] [Limone Piccolo] Lux: 1700, Temperature: 18.8, Moisture: 72, Fertility: 1481
Mar 21 10:48:41 RASPBDIETPI homebridge[457]: [3/21/2018, 10:48:41 AM] [Limone Piccolo] Firmware: 3.1.8, Battery level: 99
Mar 21 10:49:34 RASPBDIETPI homebridge[457]: [3/21/2018, 10:49:34 AM] [Ciliegio] Lux: 10775, Temperature: 7.4, Moisture: 30, Fertility: 416
Mar 21 10:49:34 RASPBDIETPI homebridge[457]: [3/21/2018, 10:49:34 AM] [Ciliegio] Firmware: 3.1.8, Battery level: 99

**Comment by honkmaster** [comment]
If you get data in the log, there must be data in the Home App...

**Comment by sorriso93** [comment]
Hello, correct. I relaunched the home app the morning after and I've got the data... Although there was a double moisture and humidity value in home and eve app... Anyway I had to remove all and I'm reinstalling homebridge and all plugins for another reason...
Do you know the periodicity of the update between homekit and the miflora sensor? I leaved the default value in the config.json as described in the readme...

**Comment by lucavb** [comment]
Not sure about your question regarding the periodicity? The readme states that the value is indicating the number of seconds between updates.

**Comment by lucavb** [comment]
Closed due to inactivity.
