### ISSUE TITLE
expected values

### ISSUE THREAD

**Issue by Pythonaire** [lucavb/homebridge-mi-flora#4]
Hi,

I try to use this great plugin for my own ESP32 sensor device. I see two Services : generally device information and the plant service). The generally device service contained a  "DATA_CHARACTERISTIC_UUID". I'm not sure, what data is expected under that characteristic. Could you explain that?

Thx

**Comment by lucavb** [comment]
Hang on. What are you trying to accomplish? Why is there an ESP32?

**Comment by Pythonaire** [comment]
Ok, thx. Finded by my self. I was a bit confused about the structure of "private BLE definition" (Services-> characteristics). Hoped I can copied the most of that and simple modify some values. Now, I make the longer work and define all that by my self. I use my own hardware,  ESP32 in that case.
