### ISSUE TITLE
Support for Xiaomi Flower Pot (Ropot)?

### ISSUE THREAD

**Issue by andreasfrank** [lucavb/homebridge-mi-flora#9]
Sorry for the question, but i couldn't find this Xiaomi device (Description: https://www.xiaomitoday.com/xiaomi-smart-flower-pot-flora-review/ ) in your list of supported devices. In the Mi Home app this device is called Ropot (availbale only with location China).
Is it supported or do you plan to support these flower pots?

Thx & Kind regards
Andreas

**Comment by lucavb** [comment]
Hey,

I am sorry but neither do I have this product nor am I really developing this plugin anymore. But maybe have a look at the forks that have sprung up. They seem to be under a more active development than this base project.
